version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes: 
      - postgres_data:/var/lib/postgresql/data
      - ../../init-db:/docker-entrypoint-initdb.d
    ports: 
      - "5433:5432"
    networks: 
      - minimart-net

networks: 
  minimart-net:
    driver: bridge

volumes:
  postgres_data: