server:
    port: 8060

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true

spring:
    cloud:
        openfeign:
            circuitbreaker:
                enabled: true
        feign:
            client:
                config:
                    default:
                        connectTimeout: 5000
                        readTimeout: 10000

resilience4j:
    circuitbreaker:
        configs:
            default:
                failureRateThreshold: 50
                slowCallRateThreshold: 100
                slowCallDurationThreshold: 5s
                permittedNumberOfCallsInHalfOpenState: 5
                maxWaitDurationInHalfOpenState: 1s
                slidingWindowType: COUNT_BASED
                slidingWindowSize: 20
                waitDurationInOpenState: 20s

        instances:
            authentication-service:
                baseConfig: default
                failureRateThreshold: 60
                waitDurationInOpenState: 15s

            profile-service:
                baseConfig: default
                failureRateThreshold: 50

            order-service:
                baseConfig: default
                failureRateThreshold: 50
                waitDurationInOpenState: 30s

    thread-pool-bulkhead:
        configs:
            default:
                maxThreadPoolSize: 8
                coreThreadPoolSize: 4
                queueCapacity: 10

        instances:
            authentication-service:
                baseConfig: default
                maxThreadPoolSize: 12
                coreThreadPoolSize: 6
                queueCapacity: 15

            profile-service:
                baseConfig: default
                maxThreadPoolSize: 6
                coreThreadPoolSize: 3

            order-service:
                baseConfig: default
                maxThreadPoolSize: 8
                coreThreadPoolSize: 4

    retry:
        configs:
            default:
                maxAttempts: 3
                waitDuration: 500ms
                retryExceptions:
                    - java.io.IOException
                    - feign.RetryableException
                ignoreExceptions:
                    - feign.FeignException$BadRequest
                    - feign.FeignException$NotFound

        instances:
            authentication-service:
                baseConfig: default
            profile-service:
                baseConfig: default
            order-service:
                baseConfig: default
