server:
    port: 8082

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true

spring:
    cloud:
        gateway:
            server:
                webflux:
                    discovery:
                        locator:
                            enabled: false
                            lower-case-service-id: true

                    routes:
                        - id: auth-mvc
                          uri: lb://authentication-service
                          predicates:
                              - Path=/login

                        - id: auth-api
                          uri: lb://authentication-service
                          predicates:
                              - Path=/api/auth/**

                        - id: profile-service
                          uri: lb://profile-service
                          predicates:
                              - Path=/api/profiles/**, /api/addresses/**
management:
    endpoint:
        gateway:
            access: unrestricted

    endpoints:
        web:
            exposure:
                include: refresh,health,info,gateway,routes
