# gateway-server.yml
server:
    port: 8082
    forward-headers-strategy: framework
    reactive:
        session:
            cookie:
                name: GWSESSION
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true

spring:
    cloud:
        gateway:
            server:
                webflux:
                    discovery:
                        locator:
                            enabled: false
                            lower-case-service-id: true

                    routes:
                        - id: auth-mvc
                          uri: lb://authentication-service
                          predicates:
                            - Path=/login/**,/logout/**,/profile/**,/oauth2/**,/.well-known/**,/error/**
                          filters:
                            - PreserveHostHeader
                            - SetResponseHeader=Referrer-Policy, strict-origin-when-cross-origin

                        - id: auth-api
                          uri: lb://authentication-service
                          predicates:
                              - Path=/v1/auth/**
                          filters:
                            - PreserveHostHeader

                        - id: profile-service
                          uri: lb://profile-service
                          predicates:
                              - Path=/v1/profiles/**, /v1/addresses/**
                          filters:
                              - RemoveRequestHeader=Authorization

                        - id: product-service
                          uri: lb://product-service
                          predicates:
                              - Path=/v1/products/**, /v1/categories/**, /v1/tags/**, /v1/admin/products/**, /v1/admin/categories/**, /v1/admin/tags/**
                          filters:
                              - RemoveRequestHeader=Authorization

                        - id: admin-bff
                          uri: lb://admin-bff
                          predicates:
                              - Path=/v1/admin/users
                          filters:
                              - RemoveRequestHeader=Authorization

                        - id: order-service
                          uri: lb://order-service
                          predicates:
                              - Path=/v1/orders/**,/v1/admin/orders/**
                          filters:
                              - RemoveRequestHeader=Authorization
                        - id: payemnt-service
                          uri: lb://order-service
                          predicates:
                              - Path=/v1/payments/**
                          filters:
                              - RemoveRequestHeader=Authorization

management:
    endpoint:
        gateway:
            access: unrestricted

    endpoints:
        web:
            exposure:
                include: refresh,health,info,gateway,routes
