server:
    port: 8082

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true

spring:
    cloud:
        gateway:
            server:
                webflux:
                    discovery:
                        locator:
                            enabled: false
                            lower-case-service-id: true

                    routes:
                        - id: auth-mvc
                          uri: lb://authentication-service
                          predicates:
                              - Path=/login

                        - id: auth-api
                          uri: lb://authentication-service
                          predicates:
                              - Path=/api/auth/**

                        - id: profile-service
                          uri: lb://profile-service
                          predicates:
                              - Path=/api/profiles/**, /api/addresses/**
                          filters:
                              - RemoveRequestHeader=Authorization

                        - id: product-service
                          uri: lb://product-service
                          predicates:
                              - Path=/api/products/**, /api/categories/**, /api/tags/**, /api/admin/products/**, /api/admin/categories/**, /api/admin/tags/**
                          filters:
                              - RemoveRequestHeader=Authorization

                        - id: admin-bff
                          uri: lb://admin-bff
                          predicates: 
                            - Path=/v1/admin/users
management:
    endpoint:
        gateway:
            access: unrestricted

    endpoints:
        web:
            exposure:
                include: refresh,health,info,gateway,routes
