server:
    port: 8084

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true

spring:
    datasource:
        driver-class-name: org.postgresql.Driver

    jpa:
        open-in-view: false
