eureka:
    client:
        service-url:
            defaultZone: http://localhost:8070/eureka/

spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/minimart-profile?createDatabaseIfNotExist=true
        username: '{cipher}0c35e06f5f24dfe55d9f62e9599249074db2df82fef2be3709c290083efbc252'
        password: '{cipher}1ca588545d584f480855460d4de9f8bf7faed630797ada8a8ca764f61b26e6e0'

    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                highlight_sql: true
        hibernate:
            ddl-auto: validate
